# Generated by Django 5.0.4 on 2024-05-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilProfesional',
            new_name='ProfesionalCV',
        ),
    ]
